module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['💜', '🌸', '🥰', '💜', '💙', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: '',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: '',
    NEWSLETTER_JID: '120363424624161926@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'GPT MINI',
    OWNER_NAME: 'SASUKE',
    OWNER_NUMBER: '94726262058',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> GPT MINI',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb7RrPKE50Uku41cMi07',
};
